### PR TITLE
fix: formatted headers

### PR DESCRIPTION
**Pull request by hongaar**
Running into this problem on GitHub. Currently, headers like
 `foo _bar_` are transformed into the anchor `foo-_bar_`. The actual anchor generated by GitHub is `foo-bar` and this breaks some functionality on GitHub when using [doctoc](https://github.com/thlorenz/doctoc) package.

This PR aims to fix this by using the [remove-markdown](https://github.com/stiang/remove-markdown) package to (surprise) remove all markdown from the header before returning the anchor.

Related to https://github.com/thlorenz/doctoc/pull/235

### CODE REVIEW

**Comment by hongaar** [comment]
> Did you double check that the existing tests still all pass?

Tests are not running on GitHub currently (need to be approved to run) but I tested this locally and they should pass.

**Comment by thlorenz** [comment]
Ah duh :) .. I kicked off CI and it's good.

> I could add more tests and run them against the current code as well to minimize the risk of breaking something not currently covered in the tests.

I would love that if you wouldn't mind.

**Comment by hongaar** [comment]
> I would love that if you wouldn't mind.

Added some more examples. I've verified these give the same results with/without the changes from this PR. If you have more/different test cases in mind, let me know and I will add those as well.

**Comment by thlorenz** [comment]
Thanks, went out as `v0.7.0` (minor update since we added a new package here and so on)

**Review by flexibrah — APPROVED** [review]

**Pull request merged**
