### PR TITLE
Add Failing Test for Exclamation Point Anchor on GitHub

### PR DESCRIPTION
**Pull request by codeblooded**
This is the failing test from #12 that shows the problem with exclamation points and GitHub anchor tags. :)

### CODE REVIEW

**Comment by thlorenz** [comment]
So if the test were to pass your problem would be solved?
How about updating this PR to include the fix, should be a simple update to the regex  used [here](https://github.com/thlorenz/anchor-markdown-header/blob/master/anchor-markdown-header.js#L23)
;)

**Comment by codeblooded** [comment]
That should be it :)

**Comment by codeblooded** [comment]
Reverted to original whitespace

**Comment by thlorenz** [comment]
Thanks, will pull tonight.

**Comment by thlorenz** [comment]
Thanks went out as 0.4.1

**Pull request closed without merging**
