### PR TITLE
Update tap version

### PR DESCRIPTION
**Pull request by RyanZim**
@thlorenz I changed the `~` to a `^`. If you don't like that, I can change it back.

### CODE REVIEW

**Comment by RyanZim** [comment]
Oops, didn't realize you tested for 0.8.

Feel free to reopen if you want to drop 0.8 support.

**Comment by thlorenz** [comment]
Yeah leave the `~` there I have a whole lot of reasons I wanna stick to that aside from `0.8`.
Mainly cause I wanna avoid issues due to deps who don't follow semver correctly breaking things from under us.

**Comment by RyanZim** [comment]
Can't upgrade tap to 7.0.0 and keep node 0.8 support; the deeper dependency tree uses `^`.

**Comment by RyanZim** [comment]
See https://travis-ci.org/thlorenz/anchor-markdown-header/builds/156633435.

**Comment by thlorenz** [comment]
OK, makes sense .. let's keep tap where it is then. Ideally we'd switch over to tape which shouldn't require too many changes, but I got zero bandwidth right now.
Also in order to make `^` work with older node we can do [something like this](https://github.com/thlorenz/sample-heap-allocations/blob/master/.travis.yml#L5-L6)

**Pull request closed without merging**
