### PR TITLE
Remove equals sign in GitHub mode

### LINKED ISSUE #11: Equals sign in header needs removing from anchor
Hi,

Using doctoc I've noticed broken links when the header contained an equals sign.

For example, a header such as `-config=<path>` gets turned into `#-config=path`, but actually GitHub uses `#-configpath`.

Thanks,

Jason

### PR DESCRIPTION
**Pull request by AndrewSouthpaw**
Fixes #11 .

### CODE REVIEW

**Comment by thlorenz** [comment]
Could you please rebase of current master, can't merge this currently without conflicts.

**Comment by thlorenz** [comment]
Made you collab, so once you rebased, please squash both commits into one, merge into master and ping me so I can publish to npm.
doctoc now allows minor updates so it will automatically get the latest anchor-markdown-header version.

Thanks.

**Comment by AndrewSouthpaw** [comment]
Will do. Also, I can add a `--ghost` flag to doctoc so it passes the mode correctly. Should I follow the same fork&pull procedure, or would you recommend something else to fit your workflow?

**Comment by thlorenz** [comment]
> I can add a --ghost flag 
I already took care of it, but I added you as collab there as well.

So now you can help with PRs, issues, merges, etc. in both repos as you see fit.

**Comment by thlorenz** [comment]
> Should I follow the same fork&pull procedure

Once I have a repo with collabs I turn it into a sort of democracy.
This means that any additions/fixes, etc. are proposed via a PR first (even by me). Then everyone can comment and when all is good the person that provided the PR merges it into master.

I only reserve the right to publish to npm which is the only privilege I have that the collabs don't.

**Pull request closed without merging**
