### PR TITLE
Fix cyrillic headers #38

### LINKED ISSUE #38: Incorrect anchor link generated when there is capital non-ascii characters in the header
[example gist](https://gist.github.com/buslov/7bd42eb87a2a082ad8eb8cece2189962)

There is old related PR for doctoc https://github.com/thlorenz/doctoc/issues/97

### PR DESCRIPTION
**Pull request by buslov**
Fix #38
toLowerCase() replaced by function that does lower case for only ASCII chars.

### CODE REVIEW

**Comment by thlorenz** [comment]
Ah interesting .. had no idea `toLowerCase` doesn't work with Cyrillic letters.
What about letters outside of `A-Z`, i.e.  the German Ä or Scandinavian Å?
Could you add some test to verify that those didn't break with your change please?

**Comment by buslov** [comment]
> Ah interesting .. had no idea toLowerCase doesn't work with Cyrillic letters.
toLowerCase() work with cyrillic fine.

But GitHub, GitLab (I can't to check BitBucket) only lower cases A-Z and leaves other chars unchanged when generating anchors.

 [Gist-example](https://gist.github.com/buslov/7bd42eb87a2a082ad8eb8cece2189962/c824f290d8a17fbbc31bcd7af618d4670312cacd)
image

[Sample snippet on GitLab](https://gitlab.com/snippets/1687375)

**Comment by thlorenz** [comment]
So looks like those extended latin are unchanged  by github and gitlab, basically behaving the way your code is ... for me chrome then url escapes this for me when hovering/clicking the link seems like.

> How should I get etalon link for testing German Ä or Scandinavian Å?

not sure what your question is, what is _etalon_?

Overall if your code does what the respective tools (github+gitlab) do then this should be fine. Still would like to publish this as a new major when merged as I'm afraid it could break some cases we haven't thought about.

Could you please add some tests for those extended latin chars, basically just to show that anchor-markdown-header doesn't lower case those anymore after your change?

Thanks

**Comment by buslov** [comment]
Add tests for extended latin chars.

> not sure what your question is, what is _etalon_?

Under _etalon_ I mean the string with what compared generated anchor (3-rd entry in rows within test array). I got ones for my tests from [gitlab snippets](https://gitlab.com/snippets/1687930).

**Comment by thlorenz** [comment]
Thanks a lot for all the work. This LGTM now and I'll publish this as a major update and the make sure doctoc uses it (also via a major version update there).

I made you collaborator so you can help me merge this in first.

Please merge to master following [this guide](https://gist.github.com/thlorenz/f7df0daf13c6f6c1fa84).
I will then version and publish to npm.

Thanks.

**Comment by antoon-r** [comment]
Hello. When will it be released and used in doctoc? New doctoc version is out but does not include this fix.

**Pull request merged**
