### PR TITLE
Added test for gitlab non alpha headers

### PR DESCRIPTION
**Pull request by mrawdon**
This its to address PR #26 it looks to already be fixed in the fix for issue #31

### CODE REVIEW

**Comment by RyanZim** [comment]
@thlorenz ping?

**Comment by thlorenz** [comment]
LGTM @RyanZim, thanks.

**Comment by RyanZim** [comment]
@thlorenz Could you make a new release?

**Comment by thlorenz** [comment]
Done @RyanZim went out as `0.5.6`.
Thanks for helping resolve this and thanks for the PR @mrawdon.

**Pull request merged**
